//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarryMe.Model.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Validation {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Validation() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MarryMe.Model.Resources.Validation", typeof(Validation).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$.
        /// </summary>
        internal static string RegexEmail {
            get {
                return ResourceManager.GetString("RegexEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Паспортные данные не прошли проверку..
        /// </summary>
        internal static string CheckPassportNum {
            get {
                return ResourceManager.GetString("CheckPassportNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нужно выбрать время в будущем..
        /// </summary>
        internal static string DateBelowNow {
            get {
                return ResourceManager.GetString("DateBelowNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Электронный адрес заполнен не правильно..
        /// </summary>
        internal static string EmailNotValid {
            get {
                return ResourceManager.GetString("EmailNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пройдите капчу..
        /// </summary>
        internal static string GetCaptcha {
            get {
                return ResourceManager.GetString("GetCaptcha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to жениха.
        /// </summary>
        internal static string Man {
            get {
                return ResourceManager.GetString("Man", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нужно указать электронную почту для подтверждения регистрации..
        /// </summary>
        internal static string NoEmailMessage {
            get {
                return ResourceManager.GetString("NoEmailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фамилию {0} нужно обязательно заполнить..
        /// </summary>
        internal static string NoLastName {
            get {
                return ResourceManager.GetString("NoLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя {0} нужно обязательно заполнить..
        /// </summary>
        internal static string NoName {
            get {
                return ResourceManager.GetString("NoName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отчество {0} нужно обязательно заполнить..
        /// </summary>
        internal static string NoSecondName {
            get {
                return ResourceManager.GetString("NoSecondName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ([0-9]{7}[A-Z][0-9]{3})((PB)|(GB)|(ВА)|(BI))[0-9].
        /// </summary>
        internal static string RegexPassId {
            get {
                return ResourceManager.GetString("RegexPassId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to невесты.
        /// </summary>
        internal static string WoMan {
            get {
                return ResourceManager.GetString("WoMan", resourceCulture);
            }
        }
    }
}
